FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    libgl1-mesa-dev \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y libglib2.0-0

WORKDIR /app

COPY . .
RUN pip3 install -r requirements.txt

EXPOSE 8501

ENTRYPOINT ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
